spring.application.name=biblioteca-api
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotecadb
spring.datasource.username=j0o0ll
spring.datasource.password=@JGrm2008
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true